# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Upsample data if frequency is 30, 60, or 90 Hertz
#' @name upSampleC
#' @param X NumericMatrix. The matrix that will be upsampled.
#' @param b_fp double. A factor to be multiplied by in the upsampling process.
#' @keywords internal
NULL

upsampleC <- function(X, b_fp) {
    .Call(`_agcounts_upsampleC`, X, b_fp)
}

