# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcalibrateC <- function(pathname = NULL, dataset = NULL, sf = NA_integer_, spherecrit = 0.3, sdcriter = 0.013, minloadcrit = 168L) {
    .Call(`_agcounts_gcalibrateC`, pathname, dataset, sf, spherecrit, sdcriter, minloadcrit)
}

#' Upsample data if frequency is 30, 60, or 90 Hertz
#' @name upSampleC
#' @param X NumericMatrix. The matrix that will be upsampled.
#' @param b_fp double. A factor to be multiplied by in the upsampling process.
#' @keywords internal
NULL

upsampleC <- function(X, b_fp) {
    .Call(`_agcounts_upsampleC`, X, b_fp)
}

